pipeline {
    agent any
    tools {
        maven "maven-3.8.2"
        jdk "JDK"
    }
    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/new/") {
                sh 'rm -rf spring-petclinic | true'
                sh 'pwd'
                sh 'git clone https://github.com/spring-projects/spring-petclinic.git'
                sh 'cd spring-petclinic'
                sh 'pwd'
                sh 'ls -lhrt'
                sh 'cd spring-petclinic && ./mvnw package'
                }
            }
        }
        stage('image build'){
            steps{
                dir("/var/lib/jenkins/workspace/new/") {
		sh 'rm -rf java-maven | true'
                sh 'git clone https://github.com/imarijitbose/java-maven.git'
                sh 'cp spring-petclinic/target/spring-petclinic-2.5.0-SNAPSHOT.jar java-maven/ && cd java-maven && docker image build -t petclinic .'
                }

            }
	}
     }
    post {
       always {
       cleanWs()
      }
   } 
}
